config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"
  resource :employees do
    match '/:id' => 'employees#change_department', via: :get, :as => 'change_department'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_one :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
       @employees = Employee.all 
    end
    def change_department
        @emp = Employee.find_by_id(params[:id])
        respond_to do |format| 
            format.html 
            format.js 
        end
    end
    def update
        @emp = Employee.find_by_id(params[:id])
        @emp.department.update(:name=>params[:department])
        @emp.save!
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_edit_dept_modal.html.erb
<div class="modal-header">
  <h5 class="modal-title"><%= name %> </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= form_tag(employees_path(),:method => :put) do %>
    <label>Department:</label>
    <select class="form-select" aria-label="Default select example" name="department">
      <option value="Product">Product</option>
      <option value="Engineering">Engineering</option>
      <option value="Finance">Finance</option>
    </select>
    <br>
    <%= hidden_field_tag "id",id%>
    <input type="submit" value="Submit" class="btn btn-primary text-center">
  <%end%>
</div>

app/views/employees/change_department.js.erb
$("#modal-window").find(".modal-content").html("<%= j render(:partial=>'employees/edit_dept_modal',:locals=>{:id=>@emp.id,:name=>[@emp.first_name,@emp.last_name].join(" ")}) %>");
$("#modal-window").modal();

app/views/employees/index.html.erb
<div class="container">
<div class="container mt-5">
<strong><h2 class="text-center">Employee List</h2></strong>
<table class="table table-bordered table-dark">
<thead>
  <tr>
    <th scope="col"><i class="fas fa-user fa-solid"></i>  First Name</th>
    <th scope="col"><i class="fas fa-user fa-solid"></i>  Last Name</th>
    <th scope="col"><i class="fas fa-bars fa-solid"></i>  Email</th>
    <th scope="col"><i class="fas fa-bars fa-solid"></i>  Phone</th>
    <th scope="col"><i class="fas fa-bars fa-solid"></i>  Salary</th>
    <th scope="col"><i class="fas fa-bars fa-solid"></i>  Department</th>
    <th scope="col"><i class="fas fa-bars fa-solid"></i>  Action</th>
    </tr>
  </thead>
  <tbody>
  <% @employees.each do |emp|%>
    <tr>
      <th scope="row"><%= emp.first_name%></th>
      <td><%= emp.last_name%></td>
      <td><%= emp.email%></td>
      <td><%= emp.phone%></td>
      <td><%= emp.salary%></td>
      <td><%= emp.department.name%></td>
      <td class="text-primary"><%= link_to 'Edit Department', change_department_employees_path(emp.id), {:remote=>true,'data-toggle': 'modal', 'data-target': '#modal-window'} %></td>
    </tr>
  <%end%>
  </tbody>
</table>
</div>
</div>


<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmpInfo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>